package captcha

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"
	"time"
)

var httpClient = &http.Client{
	Timeout: 10 * time.Second,
}

type verifyResponse struct {
	Success     bool     `json:"success"`
	ErrorCodes  []string `json:"error-codes"`
	Score       float64  `json:"score,omitempty"`
	Action      string   `json:"action,omitempty"`
}

// VerifyWithProvider checks whether the provided response/solution is valid according to the configured provider.
// If provider is "default", id is the captcha id generated by the server, and solution is the user typed answer.
// For external providers (turnstile, recaptcha_v2, recaptcha_v3, hcaptcha), solution is the client-side token,
// and secretKey is the private key configured by the administrator.
func VerifyWithProvider(ctx context.Context, provider, secretKey, id, solution, clientIP string) (bool, error) {
	switch strings.ToLower(strings.TrimSpace(provider)) {
	case "disabled":
		return true, nil

	case "turnstile":
		return verifyCloudflareTurnstile(ctx, secretKey, solution, clientIP)

	case "recaptcha_v2", "recaptcha_v3":
		return verifyGoogleRecaptcha(ctx, secretKey, solution, clientIP)

	case "hcaptcha":
		return verifyHCaptcha(ctx, secretKey, solution, clientIP)

	case "default", "":
		return Verify(id, solution), nil

	default:
		return false, fmt.Errorf("unknown captcha provider: %s", provider)
	}
}

func verifyCloudflareTurnstile(ctx context.Context, secretKey, response, remoteIP string) (bool, error) {
	if secretKey == "" || response == "" {
		return false, fmt.Errorf("missing turnstile secret or response")
	}

	data := url.Values{}
	data.Set("secret", secretKey)
	data.Set("response", response)
	if remoteIP != "" {
		data.Set("remoteip", remoteIP)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, "https://challenges.cloudflare.com/turnstile/v0/siteverify", strings.NewReader(data.Encode()))
	if err != nil {
		return false, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	resp, err := httpClient.Do(req)
	if err != nil {
		return false, fmt.Errorf("turnstile verification request failed: %w", err)
	}
	defer resp.Body.Close()

	var result verifyResponse
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return false, fmt.Errorf("failed to parse turnstile response: %w", err)
	}

	return result.Success, nil
}

func verifyGoogleRecaptcha(ctx context.Context, secretKey, response, remoteIP string) (bool, error) {
	if secretKey == "" || response == "" {
		return false, fmt.Errorf("missing recaptcha secret or response")
	}

	data := url.Values{}
	data.Set("secret", secretKey)
	data.Set("response", response)
	if remoteIP != "" {
		data.Set("remoteip", remoteIP)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, "https://www.google.com/recaptcha/api/siteverify", strings.NewReader(data.Encode()))
	if err != nil {
		return false, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	resp, err := httpClient.Do(req)
	if err != nil {
		return false, fmt.Errorf("recaptcha verification request failed: %w", err)
	}
	defer resp.Body.Close()

	var result verifyResponse
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return false, fmt.Errorf("failed to parse recaptcha response: %w", err)
	}

	return result.Success, nil
}

func verifyHCaptcha(ctx context.Context, secretKey, response, remoteIP string) (bool, error) {
	if secretKey == "" || response == "" {
		return false, fmt.Errorf("missing hcaptcha secret or response")
	}

	data := url.Values{}
	data.Set("secret", secretKey)
	data.Set("response", response)
	if remoteIP != "" {
		data.Set("remoteip", remoteIP)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, "https://hcaptcha.com/siteverify", strings.NewReader(data.Encode()))
	if err != nil {
		return false, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	resp, err := httpClient.Do(req)
	if err != nil {
		return false, fmt.Errorf("hcaptcha verification request failed: %w", err)
	}
	defer resp.Body.Close()

	var result verifyResponse
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return false, fmt.Errorf("failed to parse hcaptcha response: %w", err)
	}

	return result.Success, nil
}
